export const data = [
  {
    gadgetName: "Dell Latitude 5420",
    category: "Laptop",
    manufacturer: "Dell",
    healthRating: 95,
    techBrand: "Intel",
    userRole: "Engineer",
  },
  {
    gadgetName: "ThinkPad X1 Carbon",
    category: "Laptop",
    manufacturer: "Lenovo",
    healthRating: 40,
    techBrand: "Intel",
    userRole: "Engineer",
  },
  {
    gadgetName: "iPad Pro 12.9",
    category: "Tablet",
    manufacturer: "Apple",
    healthRating: 92,
    techBrand: "Apple Silicon",
    userRole: "Tester",
  },
  {
    gadgetName: "Galaxy Tab S9",
    category: "Tablet",
    manufacturer: "Samsung",
    healthRating: 85,
    techBrand: "Snapdragon",
    userRole: "Tester",
  },
  {
    gadgetName: "HP EliteBook 840",
    category: "Laptop",
    manufacturer: "HP",
    healthRating: 78,
    techBrand: "Intel",
    userRole: "Engineer",
  },
  {
    gadgetName: "MacBook Air M3",
    category: "Laptop",
    manufacturer: "Apple",
    healthRating: 97,
    techBrand: "Apple Silicon",
    userRole: "Tester",
  },
  {
    gadgetName: "Microsoft Surface Pro 10",
    category: "Tablet",
    manufacturer: "Microsoft",
    healthRating: 90,
    techBrand: "Intel",
    userRole: "Engineer",
  },
  {
    gadgetName: "Acer Aspire 5",
    category: "Laptop",
    manufacturer: "Acer",
    healthRating: 72,
    techBrand: "AMD",
    userRole: "Tester",
  },
  {
    gadgetName: "ASUS ROG Zephyrus G14",
    category: "Laptop",
    manufacturer: "ASUS",
    healthRating: 94,
    techBrand: "AMD",
    userRole: "Engineer",
  },
  {
    gadgetName: "Google Pixel Tablet",
    category: "Tablet",
    manufacturer: "Google",
    healthRating: 82,
    techBrand: "Tensor",
    userRole: "Tester",
  },
];
